services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    ports:
      - 13378:80
    volumes:
      - audiobookshelf-audiobooks:/audiobooks
      - audiobookshelf-podcasts:/podcasts
      - audiobookshelf-config:/config
      - audiobookshelf-metadata:/metadata
    environment:
      - TZ=America/New_York
    restart: unless-stopped

volumes:
  audiobookshelf-audiobooks:
  audiobookshelf-podcasts:
  audiobookshelf-config:
  audiobookshelf-metadata:
