apiVersion: v1
kind: Service
metadata:
  name: karakeep-nodeport
  namespace: karakeep
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: karakeep
    app.kubernetes.io/instance: karakeep
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
      nodePort: 30322







