services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    volumes:
      - n8n-data:/home/node/.n8n
      - n8n-files:/files
    environment:
      - N8N_HOST=n8n.crussell.io
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://n8n.crussell.io/
      - GENERIC_TIMEZONE=America/New_York
      - TZ=America/New_York
      - NODE_ENV=production
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
    networks:
      - n8n

volumes:
  n8n-data:
  n8n-files:

networks:
  n8n:
    driver: bridge

