apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cloudnative-pg
  namespace: kube-system
spec:
  repo: https://cloudnative-pg.github.io/charts
  chart: cloudnative-pg
  version: 0.27.0
  targetNamespace: cnpg-system
  createNamespace: true
  valuesContent: |-
    crds:
      create: true
    config:
      clusterWide: true
