version: '3.8'

services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    environment:
      - TZ=America/New_York
      - AUDIOBOOKSHELF_HOSTNAME=audiobookshelf
    volumes:
      - /mnt/swarm-data/audiobookshelf/audiobooks:/audiobooks
      - /mnt/swarm-data/audiobookshelf/config:/config
      - /mnt/swarm-data/audiobookshelf/metadata:/metadata
      - /mnt/swarm-data/audiobookshelf/podcasts:/podcasts
    ports:
      - "30337:80"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == k2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
