version: '3.8'

services:
  beszel:
    image: henrygd/beszel:latest
    ports:
      - "8090:8090"
    volumes:
      - beszel-data:/beszel_data
    networks:
      - dozzle_dozzle
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == k4
      restart_policy:
        condition: on-failure

volumes:
  beszel-data:
    driver: local

networks:
  dozzle_dozzle:
    external: true
