version: '3.8'

services:
  beszel:
    image: henrygd/beszel:latest
    ports:
      - "8090:8090"
    volumes:
      - beszel-data:/beszel_data
    networks:
      - dozzle_dozzle
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == k4
      restart_policy:
        condition: on-failure

  beszel-agent:
    image: henrygd/beszel-agent:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - beszel-agent-data:/var/lib/beszel-agent
    environment:
      - HUB_URL=http://beszel:8090
      - LISTEN=0.0.0.0:45876
    networks:
      - dozzle_dozzle
    deploy:
      mode: global
      restart_policy:
        condition: on-failure

volumes:
  beszel-data:
    driver: local
  beszel-agent-data:
    driver: local

networks:
  dozzle_dozzle:
    external: true
