version: '3.8'

services:
  beszel:
    image: henrygd/beszel:latest
    ports:
      - "8090:8090"
    volumes:
      - beszel-data:/beszel_data
    networks:
      - dozzle
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == k4
      restart_policy:
        condition: on-failure

  beszel-agent:
    image: henrygd/beszel-agent:latest
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/beszel-agent:/var/lib/beszel-agent
    networks:
      - dozzle
    deploy:
      mode: global
      restart_policy:
        condition: on-failure

volumes:
  beszel-data:
    driver: local

networks:
  dozzle:
    external: true
