version: '3.8'

services:
  dozzle:
    image: amir20/dozzle:latest
    environment:
      - DOZZLE_MODE=swarm
      - DOZZLE_ENABLE_ACTIONS=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
    networks:
      - dozzle
    deploy:
      mode: global
      restart_policy:
        condition: on-failure

  adguardhome:
    image: adguard/adguardhome:latest
    ports:
      - "30053:53/tcp"
      - "30053:53/udp"
      - "30067:67/udp"
      - "30068:68/udp"
      - "30100:80/tcp"
      - "30054:443/tcp"
      - "30101:853/tcp"
      - "30102:3000/tcp"
    volumes:
      - adguardhome-work:/opt/adguardhome/work
      - adguardhome-conf:/opt/adguardhome/conf
    networks:
      - dozzle
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == k2
      restart_policy:
        condition: on-failure

volumes:
  adguardhome-work:
    driver: local
  adguardhome-conf:
    driver: local

networks:
  dozzle:
    driver: overlay
