services:
  beszel-agent:
    image: henrygd/beszel-agent:latest
    container_name: beszel-agent
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./beszel-agent-data:/var/lib/beszel-agent
    environment:
      - HUB_URL=http://192.168.20.64:8090
      - TOKEN=702a7550-8802-4aff-99a4-2c6e9592830d
      - KEY=ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAMPLafeyw5Jh7laHQhpbZaFc8vyu1ras1XVkY3UlhQW
      - LISTEN=0.0.0.0:45876
