apiVersion: v1
kind: Namespace
metadata:
  name: open-webui
---
apiVersion: v1
kind: Service
metadata:
  name: open-webui-nodeport
  namespace: open-webui
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: open-webui
    app.kubernetes.io/instance: open-webui
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
      nodePort: 30082

