version: "3.4"

services:
  librechat-api:
    image: ghcr.io/danny-avila/librechat-dev-api:latest
    container_name: LibreChat-API
    ports:
      - 3080:3080
    depends_on:
      - librechat-mongodb
      - librechat-rag-api
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - HOST=0.0.0.0
      - MONGO_URI=mongodb://librechat-mongodb:27017/LibreChat
      - MEILI_HOST=http://librechat-meilisearch:7700
      - RAG_PORT=8000
      - RAG_API_URL=http://librechat-rag-api:8000
    volumes:
      - type: bind
        source: ./librechat.yaml
        target: /app/librechat.yaml
      - ./images:/app/client/public/images
      - ./logs:/app/api/logs
      - ./data:/app/data
    env_file:
      - .env

  librechat-mongodb:
    container_name: LibreChat-MongoDB
    image: mongo:5
    restart: always
    user: "${UID}:${GID}"
    volumes:
      - ./data-mongodb:/data/db
    command: mongod --noauth

  librechat-meilisearch:
    container_name: LibreChat-Meilisearch
    image: getmeili/meilisearch:v1.7.3
    restart: always
    environment:
      - MEILI_HOST=http://librechat-meilisearch:7700
      - MEILI_NO_ANALYTICS=true
    volumes:
      - ./data-meilisearch:/meili_data

  librechat-rag-api:
    image: ghcr.io/danny-avila/librechat-rag-api-dev-lite:latest
    container_name: LibreChat-RAG-API
    restart: always
    environment:
      - DB_HOST=librechat-vectordb
      - RAG_PORT=8000
    depends_on:
      - librechat-vectordb

  librechat-vectordb:
    image: ankane/pgvector:latest
    container_name: LibreChat-VectorDB
    restart: always
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - ./data-vectordb:/var/lib/postgresql/data

