services:
  pinepods-db:
    image: postgres:17
    container_name: pinepods-db
    restart: always
    volumes:
      - pinepods-pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=pinepods_database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=myS3curepass
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - pinepods

  pinepods-valkey:
    image: valkey/valkey:8-alpine
    restart: always
    networks:
      - pinepods

  pinepods:
    image: madeofpendletonwool/pinepods:latest
    restart: always
    ports:
      - "8040:8040"
    volumes:
      - pinepods-downloads:/opt/pinepods/downloads
      - pinepods-backups:/opt/pinepods/backups
    environment:
      - SEARCH_API_URL=https://search.pinepods.online/api/search
      - PEOPLE_API_URL=https://people.pinepods.online
      - HOSTNAME=https://pinepods.internal.crussell.io
      - DB_TYPE=postgresql
      - DB_HOST=pinepods-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=myS3curepass
      - DB_NAME=pinepods_database
      - VALKEY_HOST=pinepods-valkey
      - VALKEY_PORT=6379
      - DEBUG_MODE=false
      - PUID=911
      - PGID=911
      - TZ=America/New_York
    depends_on:
      - pinepods-db
      - pinepods-valkey
    networks:
      - pinepods

volumes:
  pinepods-pgdata:
  pinepods-downloads:
  pinepods-backups:

networks:
  pinepods:
    driver: bridge

