apiVersion: v1
kind: Service
metadata:
  name: openobserve-router-nodeport
  namespace: openobserve
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: openobserve
    app.kubernetes.io/instance: openobserve
    role: router
  ports:
    - name: http
      port: 5080
      targetPort: http
      protocol: TCP
      nodePort: 30081
