services:
  papra:
    image: ghcr.io/papra-hq/papra:latest
    container_name: papra
    ports:
      - "1221:1221"
    volumes:
      - papra-data:/app/app-data
    environment:
      - APP_BASE_URL=https://papra.internal.crussell.io
      - TZ=America/New_York
    restart: unless-stopped

volumes:
  papra-data:
    external: true
    name: papra-data


