apiVersion: v1
kind: Namespace
metadata:
  name: ntfy
---
apiVersion: v1
kind: Service
metadata:
  name: ntfy-nodeport
  namespace: ntfy
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: ntfy
    app.kubernetes.io/instance: ntfy
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30085












