apiVersion: v1
kind: Pod
metadata:
  name: db-restore-helper
  namespace: immich
spec:
  containers:
  - name: restore
    image: ghcr.io/tensorchord/cloudnative-vectorchord:16.9-0.4.3
    command: ["sleep", "3600"]
    env:
    - name: PGHOST
      value: immich-database-rw
    - name: PGPORT
      value: "5432"
    - name: PGUSER
      value: postgres
    - name: PGPASSWORD
      value: postgres_superuser_secret
    - name: PGDATABASE
      value: postgres
  restartPolicy: Never
