apiVersion: v1
kind: Pod
metadata:
  name: migration-helper
  namespace: immich
spec:
  nodeName: k4
  hostNetwork: true
  containers:
  - name: helper
    image: docker:cli
    command: ["sleep", "3600"]
    volumeMounts:
    - name: docker-sock
      mountPath: /var/run/docker.sock
  volumes:
  - name: docker-sock
    hostPath:
      path: /var/run/docker.sock
      type: Socket
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
    operator: Exists
