apiVersion: v1
kind: Service
metadata:
  name: immich-nodeport
  namespace: immich
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: server
    app.kubernetes.io/instance: immich
  ports:
    - name: http
      port: 2283
      targetPort: 2283
      protocol: TCP
      nodePort: 30081
